name: GitOps Flux Upgrade

on:
  push:
    branches:
      - main
    paths:
      - 'clusters/my-cluster/flux-system/flux-version.txt'
  workflow_dispatch:

jobs:
  upgrade-flux:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Azure login using creds
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure }}

      # 3️⃣ Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group SasinduAKS --name sasinduAKS --overwrite-existing

      # 4️⃣ Install Flux CLI (optional, for verification)
      - name: Install Flux CLI
        run: |
          sudo apt update && sudo apt install -y curl
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

      # 5️⃣ Upgrade controllers based on flux-version.txt
      - name: Upgrade selected Flux components
        run: |
          echo "Upgrading Flux components listed in flux-version.txt..."
          while IFS=: read -r deployment version; do
            deployment=$(echo $deployment | xargs)
            version=$(echo $version | xargs)
            echo "Upgrading $deployment to $version"
            kubectl -n flux-system set image deployment/$deployment manager=ghcr.io/fluxcd/$deployment:$version
          done < clusters/my-cluster/flux-system/flux-version.txt

      # 6️⃣ Verify upgrade
      - name: Verify upgraded components
        run: |
          kubectl -n flux-system get deployments -o wide
          kubectl -n flux-system get pods
