name: GitOps Flux Upgrade

on:
  push:
    branches:
      - main
    paths:
      - 'clusters/my-cluster/flux-system/flux-version.txt'
  workflow_dispatch:

jobs:
  upgrade-flux:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure }}

      # 3️⃣ Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group SasinduAKS --name sasinduAKS --overwrite-existing

      # 4️⃣ Install Flux CLI (optional, for local commands)
      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

      # 5️⃣ Upgrade Flux components based on flux-version.txt
      - name: Upgrade Flux components
        run: |
          echo "Upgrading Flux components in cluster..."
          while IFS=: read -r component version; do
            echo "Upgrading $component to $version"
            kubectl -n flux-system set image deployment/$component $component=ghcr.io/fluxcd/$component:$version
          done < clusters/my-cluster/flux-system/flux-version.txt

      # 6️⃣ Verify upgrade
      - name: Verify upgraded components
        run: |
          kubectl -n flux-system get deployments -o wide
          kubectl -n flux-system get pods
